//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace aspFirstApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Book
    {
        public Book()
        {
            this.Requests = new HashSet<Requests>();
        }
    
        public int Id { get; set; }
        public string cname { get; set; }
        public string isbn { get; set; }
        public Nullable<int> catId { get; set; }
    
        public virtual Category Category { get; set; }
        public virtual ICollection<Requests> Requests { get; set; }
    }
}
