//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace aspFirstApp.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class DB3 : DbContext
    {
        public DB3()
            : base("name=DB3")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Category> Category { get; set; }
        public virtual DbSet<Table> Table { get; set; }
        public virtual DbSet<Book> Book { get; set; }
        public virtual DbSet<signup> signup { get; set; }
        public virtual DbSet<Requests> Requests { get; set; }
        public virtual DbSet<singup> singup { get; set; }
    }
}
