//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace aspFirstApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Requests
    {
        public int Id { get; set; }
        public string email { get; set; }
        public int book_id { get; set; }
        public string status { get; set; }
        public Nullable<System.DateTime> issue_date { get; set; }
    
        public virtual Book Book { get; set; }
    }
}
