//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace aspFirstApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class signup
    {
        public int Id { get; set; }
        public string fname { get; set; }
        public string lname { get; set; }
        public string email { get; set; }
        public string gender { get; set; }
        public string batch { get; set; }
        public string roll { get; set; }
        public string pass { get; set; }
    }
}
